export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const GET_USER = "GET_USER";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const GET_APARTMENT_SUCCESS="GET_APARTMENT_SUCCESS"
export const GET_APARTMENT_FAIL="GET_APARTMENT_FAIL"
